# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
weather_data_df = pd.read_csv("../Weather_py/Outputs/Weather-data.csv", )
weather_data_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,puerto ayora,-0.74,-90.35,84.20,51,0,19.46,EC,1609363764
1,tasiilaq,65.61,-37.64,15.80,61,3,5.82,GL,1609363765
2,portobelo,9.55,-79.65,82.00,80,34,8.99,PA,1609363766
3,matias olimpio,-3.72,-42.56,84.60,55,94,5.12,BR,1609363767
4,tobe,33.74,132.79,35.01,55,100,8.01,JP,1609363769
...,...,...,...,...,...,...,...,...,...
616,san policarpo,12.18,125.51,81.07,83,99,8.43,PH,1609364527
617,cuamba,-14.80,36.54,71.64,95,100,2.17,MZ,1609364529
618,wangaratta,-36.37,146.33,69.80,60,40,4.70,AU,1609364530
619,miguel hidalgo,19.42,-99.20,69.80,30,5,13.87,MX,1609364531
620,puerto escondido,15.85,-97.07,84.20,70,20,9.17,MX,1609364532

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [42]:
locations = weather_data_df[["Lat", "Lng"]]
humidity = weather_data_df["Humidity"]

gmaps.configure(api_key="AIzaSyBODrQZh4WJ7334DbSa3H4fyVliE-xgi14")
city_data = gmaps.figure()
heat_map = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, point_radius = 2,
                               opacity=0.8,  max_intensity = 150)
city_data.add_layer(heat_map)
city_data

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [43]:
ideal_weather_df = weather_data_df.loc[(weather_data_df['Max Temp'] > 67)&
                                       (weather_data_df['Max Temp'] < 76)&
                                       (weather_data_df['Wind Speed'] <= 9)&
                                       (weather_data_df['Cloudiness'] == 0)].reset_index(drop=True)
ideal_weather_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,cape town,-33.93,18.42,68.00,68,0,4.70,ZA,1609363504
1,busselton,-33.65,115.33,71.01,52,0,4.00,AU,1609363799
2,taoudenni,22.68,-3.98,73.33,24,0,7.29,ML,1609363931
3,nioro,13.35,-15.75,75.83,45,0,5.91,GM,1609363974
4,salalah,17.02,54.09,71.60,60,0,2.24,OM,1609363799
5,viedma,-40.81,-63.00,68.00,35,0,5.01,AR,1609364146
6,dalaba,10.70,-12.25,67.64,37,0,3.27,GN,1609364221
7,dubti,11.74,41.09,71.13,56,0,8.90,ET,1609364274
8,rio tercero,-32.17,-64.11,75.99,33,0,1.99,AR,1609364277
9,umm lajj,25.02,37.27,73.36,69,0,8.41,SA,1609364374
10,massaguet,12.48,15.44,73.40,38,0,3.36,TD,1609364390

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [ ]:
hotel_df = ideal_weather_df
# hotel_df['Hotel Name'] = ""
hotels = {}
parameters = {
    'radius':5000,
    'types':'lodging',
    'key':g_key}
url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
for i, row in hotel_df.iterrows():
    lat=row['Lat']
    lng=row['Lng']
    parameters['location'] = f"{lat},{lng}"
        
    response = requests.get(url,params=parameters)
    results = response.json()
#     print(response['results'][0]['name'])
       
    try:
        hotel = results['results'][0]['name'] 
        print(hotel)
        hotels.append(hotel)
    except :
        print('Hotel not found!!')
        hotel = "Nan"
        hotels.append(hotel)

hotel_df['Hotel Name'] = hotels

hotel_df

In [ ]:
# locations = hotel_df[["Lat", "Lng"]]
# hotel_layer = gmaps.symbol_layer(
#     locations, fill_color='rgba(0, 150, 0, 0.4)',
#     stroke_color='rgba(0, 0, 150, 0.4)', scale=2,
#     info_box_content=[f"Hotels: {hotel}" for hotel in hotels]
# )


# city_data = gmaps.figure()
# city_data.add_layer(hotel_layer)

# city_data

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [ ]:
# Add marker layer ontop of heat map
locations = hotel_df[["Lat", "Lng"]]
hotel_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
city_data.add_layer(hotel_layer)

# Display figure
city_data

# Display figure